apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bede-devopsdashboard
spec:
  generators:
  - clusters: {} # This is a generator, specifically, a cluster generator.
  template: 
    # This is a template Argo CD Application, but with support for parameter substitution.
    metadata:
      name: 'bede-devopsdashboard-{{name}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/andrewmetcalfbede/csdptest
        targetRevision: restructure
        path: helm/apps
        helm:
          valueFiles:
            - values.yaml
            - values-bede-devopsdashboard-{{name}}.yaml
          values: |-
            ingress:
              host: some.host
            db:
              name: some_name
              host: some_host
      destination:
        server: '{{server}}'
        namespace: dashboard